added comments
SethWalkeroo/Quiet-Text pull request #19
Opened 2020-10-07 13:24 UTC by aish0007

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes (if any) #(issue_no) 

Replace `issue_no` with the issue number which is fixed in this PR

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/SethWalkeroo/Quiet-Text/blob/main/CONTRIBUTING.md)?

- [ ] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [ ] My works and is relatively clean. 
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

2020-10-07 19:30 UTC, SethWalkeroo requested changes
Add .idea to the .gitignore file. We don't need all of these workspace settings.

2020-10-07 23:46 UTC, SethWalkeroo approved these changes

2020-10-08 00:01 UTC, merged

2020-10-08 01:35 UTC, aish0007 commented
Thanks for merging

On Thu, 8 Oct, 2020, 5:31 am Seth Walker, <notifications@github.com> wrote:

> Merged #19 <https://github.com/SethWalkeroo/Quiet-Text/pull/19> into main.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/SethWalkeroo/Quiet-Text/pull/19#event-3852950587>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKYRMRT5X2YXWKQTBAZ5ZCTSJT6OPANCNFSM4SHMUFVQ>
> .
>

2020-10-09 00:30 UTC, SethWalkeroo commented
@all-contributors please add aish0007 for docs